print(10 + 3)
print(10 - 3)
print(10 * 3)
print(10 / 3)
print(10 % 3)
print(10 // 3)
print(10 ** 3)
print('*****************')
print(10 >= 25)
print(999< 555)
print('rayoug' >= 'Ranong')
print('*****************')
print(not True)
print(not False)
print('*****************')
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print('*****************')
print(True or True)
print(True or False)
print(False or True)
print(False or False)